export const ALL_COUNTRIES = [
    { name: 'Amerika Birleşik Devletleri', code: '+1', iso: 'us' },
    { name: 'Türkiye', code: '+90', iso: 'tr' },
    { name: 'Almanya', code: '+49', iso: 'de' },
    { name: 'Arnavutluk', code: '+355', iso: 'al' },
    { name: 'Andorra', code: '+376', iso: 'ad' },
    { name: 'Angola', code: '+244', iso: 'ao' },
    { name: 'Arjantin', code: '+54', iso: 'ar' },
    { name: 'Avusturya', code: '+43', iso: 'at' },
    { name: 'Avustralya', code: '+61', iso: 'au' },
    { name: 'Azerbaycan', code: '+994', iso: 'az' },
    { name: 'Bahreyn', code: '+973', iso: 'bh' },
    { name: 'Belçika', code: '+32', iso: 'be' },
    { name: 'Brezilya', code: '+55', iso: 'br' },
    { name: 'Birleşik Arap Emirlikleri', code: '+971', iso: 'ae' },
    { name: 'Birleşik Krallık', code: '+44', iso: 'gb' },
    { name: 'Bulgaristan', code: '+359', iso: 'bg' },
    { name: 'Cezayir', code: '+213', iso: 'dz' },
    { name: 'Çek Cumhuriyeti', code: '+420', iso: 'cz' },
    { name: 'Çin', code: '+86', iso: 'cn' },
    { name: 'Danimarka', code: '+45', iso: 'dk' },
    { name: 'Dominik Cumhuriyeti', code: '+1', iso: 'do' },
    { name: 'Ekvador', code: '+593', iso: 'ec' },
    { name: 'Endonezya', code: '+62', iso: 'id' },
    { name: 'Estonya', code: '+372', iso: 'ee' },
    { name: 'Etiyopya', code: '+251', iso: 'et' },
    { name: 'Fas', code: '+212', iso: 'ma' },
    { name: 'Filipinler', code: '+63', iso: 'ph' },
    { name: 'Finlandiya', code: '+358', iso: 'fi' },
    { name: 'Fransa', code: '+33', iso: 'fr' },
    { name: 'Güney Afrika', code: '+27', iso: 'za' },
    { name: 'Güney Kore', code: '+82', iso: 'kr' },
    { name: 'Gürcistan', code: '+995', iso: 'ge' },
    { name: 'Hırvatistan', code: '+385', iso: 'hr' },
    { name: 'Hindistan', code: '+91', iso: 'in' },
    { name: 'Hollanda', code: '+31', iso: 'nl' },
    { name: 'Honduras', code: '+504', iso: 'hn' },
    { name: 'Hong Kong', code: '+852', iso: 'hk' },
    { name: 'Irak', code: '+964', iso: 'iq' },
    { name: 'İran', code: '+98', iso: 'ir' },
    { name: 'İrlanda', code: '+353', iso: 'ie' },
    { name: 'İspanya', code: '+34', iso: 'es' },
    { name: 'İsrail', code: '+972', iso: 'il' },
    { name: 'İsveç', code: '+46', iso: 'se' },
    { name: 'İsviçre', code: '+41', iso: 'ch' },
    { name: 'İtalya', code: '+39', iso: 'it' },
    { name: 'İzlanda', code: '+354', iso: 'is' },
    { name: 'Jamaika', code: '+1', iso: 'jm' },
    { name: 'Japonya', code: '+81', iso: 'jp' },
    { name: 'Kamboçya', code: '+855', iso: 'kh' },
    { name: 'Kamerun', code: '+237', iso: 'cm' },
    { name: 'Kanada', code: '+1', iso: 'ca' },
    { name: 'Katar', code: '+974', iso: 'qa' },
    { name: 'Kazakistan', code: '+7', iso: 'kz' },
    { name: 'Kenya', code: '+254', iso: 'ke' },
    { name: 'Kırgızistan', code: '+996', iso: 'kg' },
    { name: 'Kıbrıs', code: '+357', iso: 'cy' },
    { name: 'Kolombiya', code: '+57', iso: 'co' },
    { name: 'Kosta Rika', code: '+506', iso: 'cr' },
    { name: 'Kuveyt', code: '+965', iso: 'kw' },
    { name: 'Letonya', code: '+371', iso: 'lv' },
    { name: 'Libya', code: '+218', iso: 'ly' },
    { name: 'Litvanya', code: '+370', iso: 'lt' },
    { name: 'Lüksemburg', code: '+352', iso: 'lu' },
    { name: 'Lübnan', code: '+961', iso: 'lb' },
    { name: 'Macaristan', code: '+36', iso: 'hu' },
    { name: 'Madagaskar', code: '+261', iso: 'mg' },
    { name: 'Makedonya', code: '+389', iso: 'mk' },
    { name: 'Malezya', code: '+60', iso: 'my' },
    { name: 'Malta', code: '+356', iso: 'mt' },
    { name: 'Mauritius', code: '+230', iso: 'mu' },
    { name: 'Meksika', code: '+52', iso: 'mx' },
    { name: 'Mısır', code: '+20', iso: 'eg' },
    { name: 'Moğolistan', code: '+976', iso: 'mn' },
    { name: 'Moldova', code: '+373', iso: 'md' },
    { name: 'Monako', code: '+377', iso: 'mc' },
    { name: 'Nepal', code: '+977', iso: 'np' },
    { name: 'Nijerya', code: '+234', iso: 'ng' },
    { name: 'Nikaraguay', code: '+505', iso: 'ni' },
    { name: 'Norveç', code: '+47', iso: 'no' },
    { name: 'Özbekistan', code: '+998', iso: 'uz' },
    { name: 'Pakistan', code: '+92', iso: 'pk' },
    { name: 'Panama', code: '+507', iso: 'pa' },
    { name: 'Paraguay', code: '+595', iso: 'py' },
    { name: 'Peru', code: '+51', iso: 'pe' },
    { name: 'Polonya', code: '+48', iso: 'pl' },
    { name: 'Portekiz', code: '+351', iso: 'pt' },
    { name: 'Porto Riko', code: '+1', iso: 'pr' },
    { name: 'Romanya', code: '+40', iso: 'ro' },
    { name: 'Rusya', code: '+7', iso: 'ru' },
    { name: 'Sırbistan', code: '+381', iso: 'rs' },
    { name: 'Singapur', code: '+65', iso: 'sg' },
    { name: 'Slovakya', code: '+421', iso: 'sk' },
    { name: 'Slovenya', code: '+386', iso: 'si' },
    { name: 'Sri Lanka', code: '+94', iso: 'lk' },
    { name: 'Suudi Arabistan', code: '+966', iso: 'sa' },
    { name: 'Şili', code: '+56', iso: 'cl' },
    { name: 'Tanzanya', code: '+255', iso: 'tz' },
    { name: 'Tayland', code: '+66', iso: 'th' },
    { name: 'Tayvan', code: '+886', iso: 'tw' },
    { name: 'Tunus', code: '+216', iso: 'tn' },
    { name: 'Uganda', code: '+256', iso: 'ug' },
    { name: 'Ukrayna', code: '+380', iso: 'ua' },
    { name: 'Umman', code: '+968', iso: 'om' },
    { name: 'Uruguay', code: '+598', iso: 'uy' },
    { name: 'Ürdün', code: '+962', iso: 'jo' },
    { name: 'Venezuella', code: '+58', iso: 've' },
    { name: 'Vietnam', code: '+84', iso: 'vn' },
    { name: 'Yeni Zelanda', code: '+64', iso: 'nz' },
    { name: 'Yunanistan', code: '+30', iso: 'gr' },
    { name: 'Zambiya', code: '+260', iso: 'zm' }
].sort((a, b) => (a.iso === 'us' ? -1 : b.iso === 'us' ? 1 : a.name.localeCompare(b.name)));
